schema_version: 3
base_prompt: 분리된 정사각형 9개. 3행 3열. 얇은 검은 몰딩. 탑뷰.
style_prompt: 컬러 일러스트.
default_user_prompt: 잔디밭
source_generation_id: 2026-09-30_12-39-23-04dec642
separation_size: 512
separation_steps: 4
separation_seed: 10107
