import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const writerElementLookup=new Map();
function createTestElement(){return {textContent:'',value:'',hidden:false,disabled:false,children:[],append(...currentChildrenValues){this.children.push(...currentChildrenValues);},replaceChildren(){this.children=[];}};}
const writerDocumentAdapter={createElement:createTestElement,querySelector(currentSelectorText){if(!writerElementLookup.has(currentSelectorText))writerElementLookup.set(currentSelectorText,createTestElement());return writerElementLookup.get(currentSelectorText);}};
const recordedRequestValues=[];
let currentApiState={configured:true,ready:true,trained:true,csrf_token:'test-session',document_root:'/private/documents',state_root:'/private/state',index_path:'/private/state/rag.sqlite3',jobs:[]};
let currentApiDetail={id:'test-id',status:{stage:'review',proposal_hash:'test-hash'},job_path:'/private/state/jobs/test-id',request:{mode:'write',prompt:'사용자 지시'},log:'진행 로그',proposal:{reason:'주제 일치',changes:[{path:'world/library.md',diff:'추가 문단'}],evidence:[{path:'world/library.md',heading:'기록',text:'<script>금지</script>'}],warnings:[]}};
const currentExecutionContext=vm.createContext({document:writerDocumentAdapter,setInterval(){},console,fetch:async(currentRequestUrl,currentFetchOptions)=>{recordedRequestValues.push({url:currentRequestUrl,...currentFetchOptions});if(currentRequestUrl.endsWith('/state'))return {ok:true,json:async()=>currentApiState};if(currentRequestUrl.includes('/job?'))return {ok:true,json:async()=>currentApiDetail};return {ok:true,json:async()=>({id:'test-id'})};}});
vm.runInContext(readFileSync(new URL('../manager.js',import.meta.url),'utf8'),currentExecutionContext);
await new Promise(currentResolveCallback=>setImmediate(currentResolveCallback));
await vm.runInContext('selectWriterJob("test-id")',currentExecutionContext);
assert.equal(writerDocumentAdapter.querySelector('#apply').hidden,false);
assert.match(writerDocumentAdapter.querySelector('#request').textContent,/사용자 지시/);
assert.match(writerDocumentAdapter.querySelector('#workspace').textContent,/private\/documents/);
assert.equal(writerDocumentAdapter.querySelector('#evidence').children[0].children[1].textContent,'<script>금지</script>');
writerDocumentAdapter.querySelector('#prompt').value='새 아이디어';
await vm.runInContext('submitWriterAction("write")',currentExecutionContext);
const currentWriteRequest=recordedRequestValues.find(currentRequestEntry=>currentRequestEntry.url.endsWith('/jobs'));
assert.deepEqual(JSON.parse(currentWriteRequest.body),{mode:'write',prompt:'새 아이디어'});
assert.equal(currentWriteRequest.headers['X-Writer-Token'],'test-session');
await writerDocumentAdapter.querySelector('#apply').onclick();
assert.deepEqual(JSON.parse(recordedRequestValues.find(currentRequestEntry=>currentRequestEntry.url.endsWith('/apply')).body),{id:'test-id',proposal_hash:'test-hash'});
currentApiState={...currentApiState,active_job:'running'};
await vm.runInContext('refreshWriterWorkspace()',currentExecutionContext);
assert.equal(writerDocumentAdapter.querySelector('#write').disabled,true);
assert.equal(writerDocumentAdapter.querySelector('#apply').disabled,true);
currentApiDetail={...currentApiDetail,status:{stage:'applied'},application:{status:'applied'}};
await vm.runInContext('selectWriterJob("test-id")',currentExecutionContext);
assert.equal(writerDocumentAdapter.querySelector('#apply').hidden,true);
assert.match(writerDocumentAdapter.querySelector('#applyResult').textContent,/학습/);
console.log('작가 UI: 작업 제출·세션 토큰·근거 텍스트·적용 해시·실행 중 잠금·적용 후 안내 통과');
