"""레퍼런스·이전·수정 모델 비교와 구체관절 확대 검수를 묶는다."""
from pathlib import Path
from PIL import Image
import numpy as np,json,hashlib,re,time
EXPERIMENT_OUTPUT_ROOT=Path(__file__).resolve().parent
VIEW_REFERENCE_NAMES={'front':'front','side':'left','back':'back'}
ALIGNED_IMAGE_SIZE=1024
ALIGNED_BODY_HEIGHT=900
ALIGNED_TOP_MARGIN=64
comparison_result_values={}
for view_name_value,reference_name_value in VIEW_REFERENCE_NAMES.items():
 reference_image_values=Image.open(EXPERIMENT_OUTPUT_ROOT/'inputs'/f'{reference_name_value}.png').convert('RGBA')
 reference_mask_values=np.array(reference_image_values)[:,:,3]>127
 comparison_result_values[view_name_value]={}
 for model_name_value in ['baseline','refined']:
  source_image_values=Image.open(EXPERIMENT_OUTPUT_ROOT/f'compare-{model_name_value}-{view_name_value}.png').convert('RGBA')
  cropped_image_values=source_image_values.crop(source_image_values.getchannel('A').getbbox())
  aligned_width_value=round(cropped_image_values.width*ALIGNED_BODY_HEIGHT/cropped_image_values.height)
  cropped_image_values=cropped_image_values.resize((aligned_width_value,ALIGNED_BODY_HEIGHT),Image.Resampling.LANCZOS)
  aligned_image_values=Image.new('RGBA',(ALIGNED_IMAGE_SIZE,ALIGNED_IMAGE_SIZE),(255,255,255,0))
  aligned_image_values.alpha_composite(cropped_image_values,((ALIGNED_IMAGE_SIZE-aligned_width_value)//2,ALIGNED_TOP_MARGIN))
  aligned_image_values.save(EXPERIMENT_OUTPUT_ROOT/f'aligned-{model_name_value}-{view_name_value}.png')
  model_mask_values=np.array(aligned_image_values)[:,:,3]>127
  comparison_result_values[view_name_value][model_name_value]=float(np.logical_and(reference_mask_values,model_mask_values).sum()/np.logical_or(reference_mask_values,model_mask_values).sum())
(EXPERIMENT_OUTPUT_ROOT/'reference-silhouette-comparison.json').write_text(json.dumps({'metric':'높이와 중심 정렬 후 2D alpha mask IoU','reference':'inputs/front.png, left.png, back.png','limitations':'포즈·카메라·크롭 오차가 포함된 투영 외곽 비교. 얼굴·관절 구조·전체 디자인 유사도 점수가 아님.','views':comparison_result_values},ensure_ascii=False,indent=2))
export_record_values=json.loads((EXPERIMENT_OUTPUT_ROOT/'export-validation.json').read_text())
preview_html_value='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>마네킨 체형과 구체관절 개선</title><style>:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#e9e8e3;color:#28302d;font:15px/1.65 system-ui,sans-serif}main{max-width:1260px;margin:auto;padding:32px}h1{font-size:29px;margin:0}h2{margin-top:36px}p{max-width:900px}.toolbar{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin:22px 0}button,select{padding:9px 16px;border-radius:6px;border:1px solid #a4aea7;background:white;color:#25392f}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.details{grid-template-columns:repeat(4,1fr)}.walk{grid-template-columns:repeat(4,1fr)}figure{margin:0;background:#f9faf8;border-radius:9px;overflow:hidden}img{display:block;width:100%;height:auto}figcaption{padding:10px 14px;font-weight:600}.notice{background:#fff8de;padding:13px 18px;border-radius:8px}.overlay{position:relative;background:#f9faf8;max-width:600px}.overlay img+img{position:absolute;inset:0;opacity:.5}a{color:#276544}table{border-collapse:collapse;width:100%;max-width:650px;background:white}td,th{padding:9px 14px;text-align:left;border-bottom:1px solid #dce2dc}@media(max-width:700px){main{padding:18px}.grid,.walk,.details{grid-template-columns:repeat(2,1fr)}}</style><main><h1>레퍼런스 체형 · 구체관절 개선</h1><p>어깨와 팔의 폭, 허리와 종아리를 레퍼런스에 맞춰 다듬고, 눈 렌즈와 눈썹을 추가했습니다. 어깨·고관절 소켓, 팔꿈치·무릎의 둥근 개구부, 손목·발목 연결을 조정했습니다.</p><p><a href="rigged-mannequin.blend">Blender 모델</a> · <a href="rigged-mannequin.glb">보행 GLB</a> · <a href="validation.json">리그 검증</a> · <a href="export-validation.json">GLB 검증</a> · <a href="README.md">제작 기록</a></p><div class="toolbar"><label>비교 방향 <select id="view-select"><option value="front">정면</option><option value="side">측면</option><option value="back">후면</option></select></label></div><div class="grid"><figure><img id="reference-image" src="inputs/front-preview.png"><figcaption>원본 레퍼런스</figcaption></figure><figure><img id="baseline-image" src="aligned-baseline-front.png"><figcaption>이전 모델</figcaption></figure><figure><img id="refined-image" src="aligned-refined-front.png"><figcaption>체형 · 관절 수정안</figcaption></figure></div><h2>레퍼런스 겹쳐보기</h2><div class="toolbar"><label>수정 모델 투명도 <input id="opacity-range" type="range" min="0" max="100" value="50"></label></div><div class="overlay"><img id="reference-overlay" src="inputs/front.png"><img id="refined-overlay" src="aligned-refined-front.png"></div><h2>고관절 축소와 소켓 조정</h2><div class="grid"><figure><img src="hip-before-reduction.png"><figcaption>구체가 컸던 중간 수정안</figcaption></figure><figure><img src="detail-hip.png"><figcaption>축소 · 골반 안쪽 배치</figcaption></figure></div><p>중간 수정안 대비 구체 부피 약 32% 감소. 골반 상단은 기존 허리에 맞추고, 아래쪽은 구체를 감싸는 외피로 다시 정리했습니다.</p><h2>얼굴과 구체관절 확대</h2><div class="grid details">'''
for image_name_value,label_text_value in [('detail-face','눈과 눈썹'),('detail-face-side','얼굴 측면'),('detail-shoulder','어깨 소켓'),('detail-hip','골반과 고관절'),('detail-knee','무릎 연결'),('detail-ankle','발목 연결')]:
 preview_html_value+=f'<figure><img src="{image_name_value}.png"><figcaption>{label_text_value}</figcaption></figure>'
preview_html_value+='</div><h2>보행 검수</h2><div class="toolbar"><button id="play-toggle">일시정지</button><input id="frame-range" type="range" min="1" max="8" value="1"><span id="frame-label">1 / 8</span></div><div class="grid walk">'
for view_name_value,label_text_value in [('down_left','앞 / 왼쪽'),('down_right','앞 / 오른쪽'),('up_left','뒤 / 왼쪽'),('up_right','뒤 / 오른쪽')]:
 preview_html_value+=f'<figure><img data-motion-prefix="{view_name_value}" src="{view_name_value}-01.png"><figcaption>{label_text_value}</figcaption></figure>'
preview_html_value+=f'''</div><p>{export_record_values['meshes']}개 메시 / 24개 본 / {export_record_values['triangles']:,} 삼각형 / 20fps, 1.2초 루프. 내부 구체는 강체로 유지합니다. 고관절은 골반·허벅지를 각각 구동하고, 다른 외곽 연결부만 최대 두 본을 혼합합니다.</p><h2>추가 굽힘 관찰</h2><div class="grid"><figure><img src="stress-bend-front.png"><figcaption>팔꿈치와 무릎 약 60도 굽힘</figcaption></figure><figure><img src="stress-bend-side.png"><figcaption>동일 자세 측면</figcaption></figure></div><p class="notice">추가 굽힘 이미지는 형상을 관찰하기 위한 수동 자세입니다. 모든 각도의 충돌이나 실물 조립 가능성을 검증한 결과는 아닙니다. 손발 세부와 얼굴은 추가 조형 여지가 있습니다.</p><h2>고관절 별도 관찰</h2><div class="grid"><figure><img src="hip-abduction.png"><figcaption>약 35도 벌림 관찰</figcaption></figure><figure><img src="hip-flexion.png"><figcaption>약 70도 굽힘 관찰</figcaption></figure></div><h2>레퍼런스 투영 외곽 비교</h2><table><tr><th>방향</th><th>이전</th><th>수정</th></tr>'''
for view_name_value,label_text_value in [('front','정면'),('side','측면'),('back','후면')]:
 metric_record_value=comparison_result_values[view_name_value]
 preview_html_value+=f"<tr><td>{label_text_value}</td><td>{metric_record_value['baseline']:.2%}</td><td>{metric_record_value['refined']:.2%}</td></tr>"
preview_html_value+='''</table><p>높이·중심을 맞춘 2D 외곽의 겹침(IoU)입니다. 포즈와 크롭 차이를 포함하며 얼굴이나 관절의 디자인 일치도를 의미하지 않습니다.</p></main><script>const viewSelectElement=document.querySelector('#view-select');const opacityRangeElement=document.querySelector('#opacity-range');function updateComparisonView(){const selectedViewName=viewSelectElement.value;const referenceViewName=selectedViewName==='side'?'left':selectedViewName;document.querySelector('#reference-image').src='inputs/'+referenceViewName+'-preview.png';document.querySelector('#reference-overlay').src='inputs/'+referenceViewName+'.png';document.querySelector('#baseline-image').src='aligned-baseline-'+selectedViewName+'.png';document.querySelector('#refined-image').src='aligned-refined-'+selectedViewName+'.png';document.querySelector('#refined-overlay').src='aligned-refined-'+selectedViewName+'.png';document.querySelector('#refined-overlay').style.opacity=opacityRangeElement.value/100}viewSelectElement.onchange=updateComparisonView;opacityRangeElement.oninput=updateComparisonView;let currentFrameNumber=1;let playbackActiveState=true;const frameRangeElement=document.querySelector('#frame-range');const playbackToggleElement=document.querySelector('#play-toggle');function updateMotionFrame(){for(const motionImageElement of document.querySelectorAll('[data-motion-prefix]'))motionImageElement.src=motionImageElement.dataset.motionPrefix+'-'+String(currentFrameNumber).padStart(2,'0')+'.png';frameRangeElement.value=currentFrameNumber;document.querySelector('#frame-label').textContent=currentFrameNumber+' / 8'}playbackToggleElement.onclick=()=>{playbackActiveState=!playbackActiveState;playbackToggleElement.textContent=playbackActiveState?'일시정지':'재생'};frameRangeElement.oninput=()=>{playbackActiveState=false;playbackToggleElement.textContent='재생';currentFrameNumber=Number(frameRangeElement.value);updateMotionFrame()};setInterval(()=>{if(playbackActiveState){currentFrameNumber=currentFrameNumber%8+1;updateMotionFrame()}},150);</script></html>'''
(EXPERIMENT_OUTPUT_ROOT/'preview.html').write_text(preview_html_value)
for linked_file_name in re.findall(r'(?:src|href)="([^"]+)"',preview_html_value):
 if not (EXPERIMENT_OUTPUT_ROOT/linked_file_name).is_file():raise FileNotFoundError(linked_file_name)
print(f'{time.strftime("%Y-%m-%dT%H:%M:%S%z")}/refinement-review/complete {comparison_result_values}',flush=True)
