'use strict';
const spriteElementLookup=id=>document.getElementById('sprite-'+id);
const spriteCanvasElement=spriteElementLookup('canvas'),spriteCanvasContext=spriteCanvasElement.getContext('2d');
const spriteFieldLabels={center:'원본 중심 X',floor:'원본 바닥 Y',head:'원본 머리 Y',anchorX:'기준점 X',anchorY:'기준점 Y',x:'배치 X',y:'배치 Y',scale:'배율'};
let spriteSourceRecord=null,spriteProjectDocument=null,spriteFramePosition=0,spritePlaybackTimer=null,spritePlaybackVersion=0,spriteLoadingVersion=0,spriteDirtyState=false;
const spriteImageCache=new Map(),spriteUndoRecords=[];
const spriteSelectedFrames=()=>spriteSourceRecord?.frames.filter(frame=>frame.direction===spriteElementLookup('direction').value)||[];
const spriteCurrentFrame=()=>spriteSelectedFrames()[spriteFramePosition];
const spriteCurrentSettings=()=>spriteProjectDocument?.frames[spriteCurrentFrame()?.frameId];
const spriteSetStatus=text=>spriteElementLookup('status').textContent=text;
const spriteStopPlayback=()=>{spritePlaybackVersion++;clearTimeout(spritePlaybackTimer);spritePlaybackTimer=null;};
function rememberSpriteChange(){spriteUndoRecords.push(structuredClone(spriteProjectDocument));if(spriteUndoRecords.length>40)spriteUndoRecords.shift();spriteDirtyState=true;}
function defaultSpriteSettings(frame){return {center:frame.anchor.x,floor:frame.anchor.y,head:0,anchorX:frame.anchor.x,anchorY:frame.anchor.y,x:0,y:0,scale:1};}
async function spriteCommandRequest(command,payload){const response=await fetch('/management/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:'character-animation',command,payload})});const result=await response.json();if(!response.ok||result.error)throw Error(result.error||'명령 실패');return result;}
async function loadSpriteImage(url){if(!spriteImageCache.has(url))spriteImageCache.set(url,new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>{spriteImageCache.delete(url);reject(Error('이미지 로드 실패'));};image.src=url;}));return spriteImageCache.get(url);}
function drawSpriteFrame(context,frame,settings,image){const rect=frame.rect;context.drawImage(image,rect.x,rect.y,rect.width,rect.height,256-settings.anchorX*settings.scale+settings.x,448-settings.anchorY*settings.scale+settings.y,rect.width*settings.scale,rect.height*settings.scale);}
function spritePointPosition(settings,x,y){return {x:256+(x-settings.anchorX)*settings.scale+settings.x,y:448+(y-settings.anchorY)*settings.scale+settings.y};}
function drawSpriteGuideLine(x1,y1,x2,y2,color){spriteCanvasContext.strokeStyle=color;spriteCanvasContext.beginPath();spriteCanvasContext.moveTo(x1,y1);spriteCanvasContext.lineTo(x2,y2);spriteCanvasContext.stroke();}
async function renderSpriteEditor(){
 const currentFrame=spriteCurrentFrame();if(!currentFrame)return;const renderVersion=++spriteLoadingVersion;
 try{const currentImage=await loadSpriteImage(currentFrame.url);if(renderVersion!==spriteLoadingVersion)return;
 const currentSettings=spriteCurrentSettings();spriteCanvasContext.clearRect(0,0,512,512);
 const frames=spriteSelectedFrames(),previousFrame=frames[(spriteFramePosition+frames.length-1)%frames.length];
 if(spriteElementLookup('onion').checked&&frames.length>1){const previousImage=await loadSpriteImage(previousFrame.url);if(renderVersion!==spriteLoadingVersion)return;spriteCanvasContext.globalAlpha=.22;drawSpriteFrame(spriteCanvasContext,previousFrame,spriteProjectDocument.frames[previousFrame.frameId],previousImage);spriteCanvasContext.globalAlpha=1;}
 drawSpriteFrame(spriteCanvasContext,currentFrame,currentSettings,currentImage);
 if(spriteElementLookup('guides').checked){
  const headPoint=spritePointPosition(currentSettings,currentSettings.center,currentSettings.head),floorPoint=spritePointPosition(currentSettings,currentSettings.center,currentSettings.floor);
  spriteCanvasContext.setLineDash([6,4]);drawSpriteGuideLine(256,0,256,512,'#8ff7ef');drawSpriteGuideLine(0,448,512,448,'#ffe584');drawSpriteGuideLine(0,448-Number(spriteElementLookup('height').value),512,448-Number(spriteElementLookup('height').value),'#d893fa');spriteCanvasContext.setLineDash([]);
  drawSpriteGuideLine(headPoint.x,headPoint.y,floorPoint.x,floorPoint.y,'#8ff7ef');drawSpriteGuideLine(headPoint.x-22,headPoint.y,headPoint.x+22,headPoint.y,'#d893fa');drawSpriteGuideLine(floorPoint.x-22,floorPoint.y,floorPoint.x+22,floorPoint.y,'#ffe584');
  const previousSettings=spriteProjectDocument.frames[previousFrame.frameId],previousHead=spritePointPosition(previousSettings,previousSettings.center,previousSettings.head);drawSpriteGuideLine(previousHead.x,previousHead.y,headPoint.x,headPoint.y,'#d893fa');
  const anchorPoint=spritePointPosition(currentSettings,currentSettings.anchorX,currentSettings.anchorY);drawSpriteGuideLine(anchorPoint.x-8,anchorPoint.y,anchorPoint.x+8,anchorPoint.y,'#ff827a');drawSpriteGuideLine(anchorPoint.x,anchorPoint.y-8,anchorPoint.x,anchorPoint.y+8,'#ff827a');
 }
 for(const fieldName of Object.keys(spriteFieldLabels))spriteElementLookup('field-'+fieldName).value=currentSettings[fieldName];
 spriteElementLookup('timeline').max=frames.length-1;spriteElementLookup('timeline').value=spriteFramePosition;spriteElementLookup('position').textContent=`${spriteFramePosition+1} / ${frames.length} · ${spriteSourceRecord.fps} FPS`;
 document.querySelectorAll('#sprite-strip button').forEach((button,index)=>button.setAttribute('aria-pressed',String(index===spriteFramePosition)));
 }catch(error){spriteStopPlayback();spriteSetStatus(error.message);}
}
function rebuildSpriteStrip(){spriteElementLookup('strip').replaceChildren(...spriteSelectedFrames().map((frame,index)=>{const button=document.createElement('button');button.textContent=String(index+1);button.setAttribute('aria-label','프레임 '+(index+1));button.onclick=()=>{spriteStopPlayback();spriteFramePosition=index;renderSpriteEditor();};return button;}));spriteFramePosition=0;renderSpriteEditor();}
async function openSpriteSource(id){
 if(spriteDirtyState&&!confirm('저장하지 않은 편집이 있습니다. 다른 원본을 불러올까요?'))return;
 spriteStopPlayback();const loadingVersion=++spriteLoadingVersion;spriteSetStatus('원본과 저장된 편집을 불러오는 중…');
 try{const source=await spriteCommandRequest('sprite-source',{id}),saved=await spriteCommandRequest('sprite-load',{id});if(loadingVersion!==spriteLoadingVersion)return;
 const loadedDocument=saved.document||{version:1,source:id,frames:Object.fromEntries(source.frames.map(frame=>[frame.frameId,defaultSpriteSettings(frame)]))};
 if(source.frames.some(frame=>!loadedDocument.frames[frame.frameId]))throw Error('원본 프레임이 변경되었습니다. 저장된 편집과 비교가 필요합니다.');
 spriteSourceRecord=source;spriteProjectDocument=loadedDocument;if(source.source?.gameRenderMetrics?.characterHeight)spriteElementLookup('height').value=source.source.gameRenderMetrics.characterHeight;
 spriteUndoRecords.length=0;spriteDirtyState=false;spriteImageCache.clear();spriteElementLookup('direction').replaceChildren(...[...new Set(source.frames.map(frame=>frame.direction))].map(direction=>new Option(({down_left:'전방 좌측',down_right:'전방 우측',up_left:'후방 좌측',up_right:'후방 우측'})[direction]||direction,direction)));rebuildSpriteStrip();spriteSetStatus((saved.warning?saved.warning+' · ':'')+source.label+' · '+(saved.revision?'저장본 '+saved.revision:'새 편집 · 머리·바닥 가이드를 먼저 지정하세요.'));
 }catch(error){spriteSetStatus(error.message);}
}
for(const [field,label] of Object.entries(spriteFieldLabels)){const input=document.createElement('input');input.type='number';input.step=field==='scale'?'0.01':'1';input.id='sprite-field-'+field;const wrapper=document.createElement('label');wrapper.textContent=label.replace('원본','원본');wrapper.append(input);spriteElementLookup('fields').append(wrapper);input.onchange=()=>{if(!spriteCurrentSettings())return;const value=Number(input.value);if(!Number.isFinite(value)||(field==='scale'&&(value<.01||value>8))){spriteSetStatus('좌표 또는 배율을 확인하세요.');renderSpriteEditor();return;}spriteStopPlayback();rememberSpriteChange();spriteCurrentSettings()[field]=value;renderSpriteEditor();};}
spriteElementLookup('load').onclick=()=>openSpriteSource(spriteElementLookup('job').value.trim());
spriteElementLookup('asset-load').onclick=()=>{if(spriteElementLookup('asset').value)openSpriteSource(spriteElementLookup('asset').value);};
spriteElementLookup('direction').onchange=()=>{spriteStopPlayback();rebuildSpriteStrip();};
for(const name of ['guides','onion','height'])spriteElementLookup(name).onchange=renderSpriteEditor;
for(const [name,delta] of [['prev',-1],['next',1]])spriteElementLookup(name).onclick=()=>{if(!spriteCurrentFrame())return;spriteStopPlayback();spriteFramePosition=(spriteFramePosition+delta+spriteSelectedFrames().length)%spriteSelectedFrames().length;renderSpriteEditor();};
spriteElementLookup('timeline').oninput=()=>{spriteStopPlayback();spriteFramePosition=Number(spriteElementLookup('timeline').value);renderSpriteEditor();};
spriteElementLookup('stop').onclick=spriteStopPlayback;
spriteElementLookup('play').onclick=()=>{if(!spriteCurrentFrame())return;spriteStopPlayback();const playbackVersion=spritePlaybackVersion;const advance=async()=>{spriteFramePosition=(spriteFramePosition+1)%spriteSelectedFrames().length;await renderSpriteEditor();if(playbackVersion===spritePlaybackVersion&&spritePlaybackTimer!==null)spritePlaybackTimer=setTimeout(advance,1000/spriteSourceRecord.fps);};spritePlaybackTimer=setTimeout(advance,1000/spriteSourceRecord.fps);};
function alignSpriteSettings(normalize){if(!spriteCurrentSettings())return;spriteStopPlayback();const settings=spriteCurrentSettings(),height=Number(spriteElementLookup('height').value),scale=height/(settings.floor-settings.head);if(settings.floor<=settings.head||!Number.isFinite(scale)||scale<.01||scale>8){spriteSetStatus('머리선은 바닥선보다 위에 있어야 하며 배율은 0.01~8이어야 합니다.');return;}rememberSpriteChange();settings.anchorX=settings.center;settings.anchorY=settings.floor;settings.x=0;settings.y=0;if(normalize)settings.scale=scale;renderSpriteEditor();}
spriteElementLookup('align').onclick=()=>alignSpriteSettings(false);spriteElementLookup('normalize').onclick=()=>alignSpriteSettings(true);
spriteElementLookup('apply').onclick=()=>{if(!spriteCurrentSettings())return;spriteStopPlayback();rememberSpriteChange();const scope=spriteElementLookup('scope').value,frames=scope==='clip'?spriteSourceRecord.frames:scope==='direction'?spriteSelectedFrames():[spriteCurrentFrame()],settings=structuredClone(spriteCurrentSettings());for(const frame of frames)spriteProjectDocument.frames[frame.frameId]=structuredClone(settings);renderSpriteEditor();spriteSetStatus(frames.length+'프레임에 현재 설정 적용 · 저장 전 상태');};
spriteElementLookup('undo').onclick=()=>{if(!spriteUndoRecords.length)return;spriteStopPlayback();spriteProjectDocument=spriteUndoRecords.pop();spriteDirtyState=true;renderSpriteEditor();};
spriteElementLookup('reset').onclick=()=>{if(!spriteCurrentFrame())return;spriteStopPlayback();rememberSpriteChange();spriteProjectDocument.frames[spriteCurrentFrame().frameId]=defaultSpriteSettings(spriteCurrentFrame());renderSpriteEditor();};
spriteElementLookup('save').onclick=async()=>{if(!spriteProjectDocument)return;const snapshot=structuredClone(spriteProjectDocument);try{const saved=await spriteCommandRequest('sprite-save',{id:snapshot.source,document:snapshot});if(JSON.stringify(snapshot)===JSON.stringify(spriteProjectDocument))spriteDirtyState=false;spriteSetStatus('저장 완료 · '+saved.revision+' · '+saved.path);}catch(error){spriteSetStatus(error.message);}};
function downloadSpriteBlob(blob,name){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
spriteElementLookup('json').onclick=()=>{if(spriteProjectDocument)downloadSpriteBlob(new Blob([JSON.stringify({project:spriteProjectDocument,source:spriteSourceRecord,output:{width:512,height:512,anchor:{x:256,y:448},fps:spriteSourceRecord.fps}},null,2)],{type:'application/json'}),'sprite-normalization.json');};
spriteElementLookup('png').onclick=async()=>{if(!spriteCurrentFrame())return;spriteStopPlayback();const frames=structuredClone(spriteSelectedFrames()),document=structuredClone(spriteProjectDocument),columns=Math.min(8,frames.length);if(frames.length>128){spriteSetStatus('PNG 시트는 방향당 128프레임까지 지원합니다.');return;}const canvas=window.document.createElement('canvas');canvas.width=columns*512;canvas.height=Math.ceil(frames.length/columns)*512;const context=canvas.getContext('2d');try{for(let index=0;index<frames.length;index++){const frame=frames[index],image=await loadSpriteImage(frame.url);context.save();context.beginPath();context.rect(index%columns*512,Math.floor(index/columns)*512,512,512);context.clip();context.translate(index%columns*512,Math.floor(index/columns)*512);drawSpriteFrame(context,frame,document.frames[frame.frameId],image);context.restore();}canvas.toBlob(blob=>{if(blob)downloadSpriteBlob(blob,'sprite-'+frames[0].direction+'.png');},'image/png');spriteSetStatus('정렬한 PNG 시트 다운로드 · 배경과 투명도는 원본을 유지합니다.');}catch(error){spriteSetStatus(error.message);}};
let spriteDragOrigin=null;
spriteCanvasElement.onpointerdown=event=>{if(!spriteCurrentSettings())return;spriteStopPlayback();const bounds=spriteCanvasElement.getBoundingClientRect(),point={x:(event.clientX-bounds.left)*512/bounds.width,y:(event.clientY-bounds.top)*512/bounds.height},settings=spriteCurrentSettings();rememberSpriteChange();const mode=spriteElementLookup('mode').value;if(mode==='move'){spriteDragOrigin={point,x:settings.x,y:settings.y};spriteCanvasElement.setPointerCapture(event.pointerId);}else{const x=(point.x-256-settings.x)/settings.scale+settings.anchorX,y=(point.y-448-settings.y)/settings.scale+settings.anchorY;if(mode==='anchor'){settings.anchorX=Math.round(x);settings.anchorY=Math.round(y);}else settings[mode]=Math.round(mode==='center'?x:y);renderSpriteEditor();}};
spriteCanvasElement.onpointermove=event=>{if(!spriteDragOrigin)return;const bounds=spriteCanvasElement.getBoundingClientRect(),settings=spriteCurrentSettings();settings.x=Math.round(spriteDragOrigin.x+(event.clientX-bounds.left)*512/bounds.width-spriteDragOrigin.point.x);settings.y=Math.round(spriteDragOrigin.y+(event.clientY-bounds.top)*512/bounds.height-spriteDragOrigin.point.y);renderSpriteEditor();};
spriteCanvasElement.onpointerup=spriteCanvasElement.onpointercancel=()=>{spriteDragOrigin=null;};
window.addEventListener('beforeunload',event=>{if(spriteDirtyState){event.preventDefault();event.returnValue='';}});
for(const name of ['review-pane-hidden','visibilitychange'])document.addEventListener(name,()=>{if(name==='review-pane-hidden'||document.hidden)spriteStopPlayback();});
fetch('/sprite-assets.json').then(response=>{if(!response.ok)throw Error('프론트 에셋 목록을 다시 빌드해야 합니다.');return response.json();}).then(catalog=>spriteElementLookup('asset').append(...catalog.assets.map(asset=>new Option(asset.label,asset.id)))).catch(error=>spriteSetStatus(error.message));
