schema_version: 1
prefabs:
  - id: iseulon-guild
    roof_tile: marble_roof
    ground_floor_plain_wall_tile: marble_plain_wall
    ground_floor_small_window_wall_tile: marble_small_window_wall
    upper_floor_large_window_wall_tile: marble_large_window_wall
    door_tile: marble_small_door
  - id: iseulon-bookshop
    roof_tile: wood_roof
    ground_floor_plain_wall_tile: wood_wall
    ground_floor_small_window_wall_tile: wood_window_wall
    upper_floor_large_window_wall_tile: wood_window_wall
    roof_underlay_wall_tile: wood_crossbar_wall
    door_tile: wood_door_wall
  - id: iseulon-inn
    roof_tile: wood_roof
    ground_floor_plain_wall_tile: wood_wall
    ground_floor_small_window_wall_tile: wood_window_wall
    upper_floor_large_window_wall_tile: wood_window_wall
    roof_underlay_wall_tile: wood_crossbar_wall
    door_tile: wood_door_wall
  - id: iseulon-workshop
    roof_tile: marble_roof
    ground_floor_plain_wall_tile: marble_plain_wall
    ground_floor_small_window_wall_tile: marble_small_window_wall
    upper_floor_large_window_wall_tile: marble_large_window_wall
    door_tile: marble_small_door
  - id: iseulon-market
    roof_tile: marble_roof
    ground_floor_plain_wall_tile: marble_plain_wall
    ground_floor_small_window_wall_tile: marble_small_window_wall
    upper_floor_large_window_wall_tile: marble_large_window_wall
    door_tile: marble_small_door
