import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const reviewHtmlContent=readFileSync(process.argv[2],'utf8');
const reviewScriptContent=reviewHtmlContent.split('<script>')[1].split('</script>')[0];
const elementLookupTable=new Map();
const canvasTraceOperations=[];
const mockCanvasContext=new Proxy({}, {get:(currentCanvasTarget,currentOperationName)=>(...currentOperationArguments)=>{canvasTraceOperations.push([currentOperationName,...currentOperationArguments]);}});
function selectMockElement(selectorQueryText){if(!elementLookupTable.has(selectorQueryText))elementLookupTable.set(selectorQueryText,{value:selectorQueryText==='#directionChoice'?'down_left':selectorQueryText==='#pointChoice'?'anchor':'0',textContent:'',innerHTML:'',checked:true,getContext:()=>mockCanvasContext});return elementLookupTable.get(selectorQueryText)}
const fakeDocumentAdapter={querySelector:selectMockElement,querySelectorAll:()=>[],createElement:()=>({click(){}})};
const testExecutionContext=vm.createContext({document:fakeDocumentAdapter,Image:class{set src(sourceImageLocation){if(this.onload)this.onload()}},requestAnimationFrame(){},performance:{now:()=>0},canvasTraceOperations,URL,Blob,setTimeout});
vm.runInContext(reviewScriptContent,testExecutionContext);
vm.runInContext(`
const originalFirstFrameCopy=JSON.stringify(reviewFrameRecords[0]);
const originalSecondAnchorX=reviewFrameRecords[1].anchor.x;
document.querySelector('#nextFrame').onclick();
if(frameChoiceElement.value!=='1'||animationPlaybackActive)throw new Error('다음 프레임은 일시정지해야 함');
moveSelectedPoint(1,0);
if(reviewFrameRecords[1].anchor.x!==originalSecondAnchorX+1)throw new Error('1px 이동 오류');
if(JSON.stringify(reviewFrameRecords[0])!==originalFirstFrameCopy)throw new Error('다른 프레임 변경');
document.querySelector('#previousFrame').onclick();
if(frameChoiceElement.value!=='0')throw new Error('이전 프레임 오류');
document.querySelector('#previousFrame').onclick();
if(frameChoiceElement.value!=='7')throw new Error('프레임 순환 오류');
const originalCoordinateExport=JSON.stringify(buildCoordinateArtifact());
previewTileWidthElement.value='320';
if(!updatePreviewGroundSize()||previewTileWidthValue!==320||previewTileHeightValue!==160)throw new Error('가상 타일 크기 적용 실패');
canvasTraceOperations.length=0;drawPreviewGroundPlane();
const initialShadowOperation=canvasTraceOperations.find(currentOperationRecord=>currentOperationRecord[0]==='ellipse');
if(initialShadowOperation[3]!==80||initialShadowOperation[4]!==40)throw new Error('그림자 50% 비율 오류');
previewTileWidthElement.value='600';updatePreviewGroundSize();
if(previewTileHeightValue!==300||calculatePreviewGroundHeight()+previewTileHeightValue/2>REVIEW_CANVAS_HEIGHT-PREVIEW_GROUND_BOTTOM_MARGIN)throw new Error('최대 타일 비율 또는 경계 오류');
canvasTraceOperations.length=0;drawPreviewGroundPlane();
const enlargedShadowOperation=canvasTraceOperations.find(currentOperationRecord=>currentOperationRecord[0]==='ellipse');
if(enlargedShadowOperation[3]!==150||enlargedShadowOperation[4]!==75)throw new Error('그림자 확대 비례 오류');
previewTileWidthElement.value='321';if(updatePreviewGroundSize())throw new Error('짝수가 아닌 너비 허용');
previewTileWidthElement.value='-1';
if(updatePreviewGroundSize()!==false||previewTileWidthValue!==600)throw new Error('잘못된 타일 크기 허용');
canvasTraceOperations.length=0;drawPreviewGroundPlane();
if(!canvasTraceOperations.some(currentOperationRecord=>currentOperationRecord[0]==='ellipse'))throw new Error('그림자 미표시');
document.querySelector('#shadowPreviewToggle').checked=false;
canvasTraceOperations.length=0;drawPreviewGroundPlane();
if(canvasTraceOperations.some(currentOperationRecord=>currentOperationRecord[0]==='ellipse'))throw new Error('그림자 숨김 실패');
if(JSON.stringify(buildCoordinateArtifact())!==originalCoordinateExport)throw new Error('표시 설정이 좌표 내보내기를 변경함');
const exportedArtifactValue=buildCoordinateArtifact();
if(exportedArtifactValue.frames.length!==32||!exportedArtifactValue.description||exportedArtifactValue.source.sheets.length!==4)throw new Error('내보내기 메타데이터 누락');
for(const frameRecordValue of exportedArtifactValue.frames)for(const pointRecordValue of [...frameRecordValue.points,frameRecordValue.anchor])if(!Number.isInteger(pointRecordValue.x)||!Number.isInteger(pointRecordValue.y))throw new Error('정수 좌표 아님');
`,testExecutionContext);
assert.equal(vm.runInContext('buildCoordinateArtifact().artifactType',testExecutionContext),'character-animation-anchor-review');
console.log('프레임 전환·1px 이동·다른 프레임 보존·정수 JSON 내보내기·가상 타일·그림자 검사 통과');
